# API KEY
apiVersion: passport/v1
kind: ApiKey
metadata:
  name: dating-asset-api-key
spec:
  name: Secret Api Key For Dating
  policies:
    - BucketFullAccess
    - FunctionFullAccess
    - IdentityFullAccess
---
# BUCKET - Interests
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-dating-asset-interests-bucket
spec:
  title: Interests
  description: Describe your new bucket
  icon: group_add
  primary: interest
  readOnly: false
  history: false
  properties:
    interest:
      type: string
      description: Description of the interest input
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 110
---
# BUCKET - User
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-dating-asset-user-bucket
spec:
  title: User
  description: Describe your new bucket
  icon: group_add
  primary: name
  readOnly: false
  history: false
  properties:
    identity_id:
      type: string
      description: Description of the identity_id input
      options:
        position: left
    name:
      type: string
      description: Description of the name input
      options:
        position: left
        translate: false
    surname:
      type: string
      description: Description of the surname input
      options:
        position: left
    email:
      type: string
      description: Description of the email input
      options:
        position: left
        unique: true
    username:
      type: string
      description: Description of the username input
      options:
        position: left
        unique: true
    phone:
      type: string
      description: Description of the phone input
      options:
        position: right
    city:
      type: string
      description: Description of the city input
      options:
        position: right
    country:
      type: string
      description: Description of the country input
      options:
        position: right
    gender:
      type: string
      description: Description of the gender input
      options:
        position: right
      enum:
        - male
        - female
        - other
    school:
      type: string
      description: Description of the school input
      options:
        position: bottom
    description:
      type: textarea
      description: Description of the description input
      options:
        position: right
    birthday:
      type: date
      description: Description of the birthday input
      options:
        position: bottom
    profile_photo:
      type: storage
      description: Description of the profile_photo input
      options:
        position: bottom
    gallery:
      type: array
      description: Description of the gallery input
      options:
        position: bottom
      items:
        title: photos
        type: storage
    created_at:
      type: date
      description: Description of the created_at input
      options:
        position: bottom
      default: :created_at
    updated_at:
      type: date
      description: Description of the updated_at input
      options:
        position: bottom
      default: :updated_at
    location:
      type: location
      description: Description of the location input
      options:
        position: bottom
      locationType: Point
    preferred_match_gender:
      type: string
      description: Description of the preferred_match_gender input
      options:
        position: bottom
      enum:
        - male
        - female
        - others
        - all
    job:
      type: string
      description: Description of the job input
      options:
        position: bottom
    max_distance:
      type: string
      description: Max distance or max diameter of search area
      options:
        position: bottom
    age_range_start:
      type: number
      description: Match age ranging minimum
      options:
        position: bottom
      minimum: 18
    age_range_end:
      type: number
      description: Match age ranging maximum
      options:
        position: bottom
      minimum: 18
      maximum: 100
    visible:
      type: boolean
      description: This user will be visible or not
      options:
        position: bottom
      default: false
    interests:
      type: relation
      description: Users interests
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-dating-asset-interests-bucket
    fcm_token:
      type: string
      description: Description of the fcm_token input
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 111
---
# BUCKET - Likes
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-dating-asset-likes-bucket
spec:
  title: Likes
  description: Describe your new bucket
  icon: group_add
  primary: like_type
  readOnly: false
  history: false
  properties:
    user:
      type: relation
      description: Description of the user input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    liked_user:
      type: relation
      description: Description of the liked_user input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    like_type:
      type: string
      description: Description of the like_type input
      options:
        position: bottom
      enum:
        - like
        - superlike
      default: like
    created_at:
      type: date
      description: Description of the created_at input
      options:
        position: bottom
      default: :created_at
    matched:
      type: boolean
      description: AUTO FILL - If the user has matched with this like or not
      options:
        position: bottom
      default: false
  acl:
    write: true==true
    read: true==true
  order: 112
---
# BUCKET - Unlikes
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-dating-asset-unlikes-bucket
spec:
  title: Unlikes
  description: Describe your new bucket
  icon: group_add
  primary: primary
  readOnly: false
  history: false
  properties:
    user:
      type: relation
      description: Description of the user input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    unliked_user:
      type: relation
      description: Description of the unliked_user input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    created_at:
      type: date
      description: Description of the created_at input
      options:
        position: bottom
      default: :created_at
    primary:
      type: string
      description: This field is just for preventing primary key error
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 113
---
# BUCKET - Match
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-dating-asset-match-bucket
spec:
  title: Match
  description: Describe your new bucket
  icon: group_add
  primary: user1_like_type
  readOnly: false
  history: false
  properties:
    user1:
      type: relation
      description: Description of the user1 input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    user2:
      type: relation
      description: Description of the user2 input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    user1_like_type:
      type: string
      description: Description of the user1_like_type input
      options:
        position: bottom
      enum:
        - like
        - superlike
    user2_like_type:
      type: string
      description: Description of the user2_like_type input
      options:
        position: bottom
      enum:
        - like
        - superlike
    created_at:
      type: date
      description: Description of the created_at input
      options:
        position: bottom
      default: :created_at
  acl:
    write: true==true
    read: true==true
  order: 114
---
# BUCKET - Chat
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-dating-asset-chat-bucket
spec:
  title: Chat
  description: Describe your new bucket
  icon: group_add
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Description of the name input
      options:
        position: left
    managers:
      type: relation
      title: managers
      description: Description of the managers input
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    informations:
      type: array
      title: informations
      description: Description of the last_active input
      options:
        position: right
      items:
        title: Items
        type: object
        properties:
          date:
            type: date
            title: date
            description: Description of the date input
            options:
              position: bottom
            default: :created_at
          user:
            type: relation
            title: user
            description: Description of the user input
            options:
              position: bottom
            relationType: onetoone
            dependent: false
            bucket:
              resourceFieldRef:
                schemaName: spica-dating-asset-user-bucket
          unread_messages_count:
            type: number
            title: unread_messages_count
            description: Description of the unread_messages_count input
            options:
              position: bottom
            default: 0
          status:
            type: string
            title: status
            description: Description of the status input
            options:
              position: bottom
            enum:
              - active
              - deleted
              - requested
            default: active
    last_message:
      type: string
      title: last_message
      description: Description of the last_message input
      options:
        position: left
    last_message_time:
      type: date
      title: last_message_time
      description: Description of the last_message_time input
      options:
        position: left
    last_message_owner:
      type: relation
      title: last_message_owner
      description: Description of the last_message_owner input
      options:
        position: left
      relationType: onetoone
      dependent: false
      primary: username
      bucket:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    is_group:
      type: boolean
      title: is_group
      description: Description of the is_group input
      options:
        position: bottom
      default: false
    image:
      type: storage
      title: image
      description: Description of the image input
      options:
        position: bottom
    created_at:
      type: date
      title: created_at
      description: Description of the created_at input
      options:
        position: left
      default: :created_at
  acl:
    write: true==true
    read: true==true
  order: 115
---
# BUCKET - Message
apiVersion: bucket/v1
kind: Schema
metadata:
  name: spica-dating-asset-message-bucket
spec:
  title: Message
  description: Describe your new bucket
  icon: group_add
  primary: message
  readOnly: false
  history: false
  properties:
    message:
      type: string
      title: message
      description: Description of the message input
      options:
        position: bottom
    owner:
      type: relation
      title: owner
      description: Description of the owner input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: username
      bucket:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    chat:
      type: relation
      title: chat
      description: Description of the chat input
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: spica-dating-asset-chat-bucket
    image:
      type: storage
      title: image
      description: Description of the image input
      options:
        position: bottom
    created_at:
      type: date
      title: created_at
      description: Description of the created_at input
      options:
        position: bottom
      default: :created_at
  acl:
    write: true==true
    read: true==true
  order: 5
---
# FUNCTION -  Match detector
apiVersion: function/v1
kind: Function
metadata:
  name: spica-dating-asset-match-detector-function
spec:
  description: Match detector from the likes
  language: javascript
  timeout: 10
  environment:
    - name: MATCH_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: spica-dating-asset-match-bucket
    - name: API_KEY
      valueFrom:
        resourceFieldRef:
          apiKeyName: dating-asset-api-key
  dependency:
    - name: "@spica-devkit/bucket"
      version: latest
  title: Match detector
  code: ./function/spica-dating-asset-match-detector-function.js
  runtime:
    name: Node
    language: Javascript
---
# FUNCTION -  Get suitable users
apiVersion: function/v1
kind: Function
metadata:
  name: spica-dating-asset-get-suitable-users-function
spec:
  description: Getting suitable users with filtering liked and unliked users
  language: javascript
  timeout: 26
  environment:
    - name: USER_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    - name: API_KEY
      valueFrom:
        resourceFieldRef:
          apiKeyName: dating-asset-api-key
    - name: LIKES_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: spica-dating-asset-likes-bucket
    - name: UNLIKES_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: spica-dating-asset-unlikes-bucket
  dependency:
    - name: "@spica-devkit/bucket"
      version: latest
  title: Get suitable users
  code: ./function/spica-dating-asset-get-suitable-users-function.js
  runtime:
    name: Node
    language: Javascript
---
# FUNCTION - Set Online
apiVersion: function/v1
kind: Function
metadata:
  name: spica-dating-asset-set-online-function
spec:
  description: Set Online Operation
  language: javascript
  timeout: 12
  environment:
    - name: IDENTITIY_SECRET_KEY
      valueFrom:
        resourceFieldRef:
          apiKeyName: dating-asset-api-key
    - name: USERS_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    - name: CHATS_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: spica-dating-asset-chat-bucket
  dependency:
    - name: "@spica-devkit/database"
      version: latest
    - name: "@spica-devkit/identity"
      version: latest
  title: Set Online
  code: ./function/spica-dating-asset-set-online-function.js
  runtime:
    name: Node
    language: Javascript
---
# FUNCTION - Dating Authorization
apiVersion: function/v1
kind: Function
metadata:
  name: spica-dating-asset-authorization-function
spec:
  language: javascript
  timeout: 25
  description: Authorization process
  environment:
    - name: USER_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: spica-dating-asset-user-bucket
    - name: SECRET_API_KEY
      valueFrom:
        resourceFieldRef:
          apiKeyName: dating-asset-api-key
  dependency:
    - name: "@spica-devkit/bucket"
      version: latest
    - name: "@spica-devkit/identity"
      version: latest
  title: Dating Authorization
  code: ./function/spica-dating-asset-authorization-function.js
  runtime:
    name: Node
    language: Javascript
---
# TRIGGER - register
apiVersion: function/v1
kind: Trigger
metadata:
  name: register
spec:
  type: http
  active: true
  name: register
  func: spica-dating-asset-authorization-function
  httpOptions:
    method: Post
    path: /register
---
# TRIGGER - default
apiVersion: function/v1
kind: Trigger
metadata:
  name: default
spec:
  type: http
  active: true
  name: default
  func: spica-dating-asset-set-online-function
  httpOptions:
    method: Post
    path: /online
---
# TRIGGER - matchDetector
apiVersion: function/v1
kind: Trigger
metadata:
  name: matchDetector
spec:
  type: bucket
  active: true
  name: matchDetector
  func: spica-dating-asset-match-detector-function
  bucketOptions:
    bucket:
      resourceFieldRef:
        schemaName: spica-dating-asset-likes-bucket
    type: INSERT
---
# TRIGGER - getUsers
apiVersion: function/v1
kind: Trigger
metadata:
  name: getUsers
spec:
  type: http
  active: true
  batch:
    deadline: 25
    limit: 9007199254740991
  name: getUsers
  func: get-suitable-users
  httpOptions:
    method: Get
    path: /getUsers
